openapi: 3.1.0
info:
 title: bookLister API
 license:
   name: BSD-3 Clause
   url: https://opensource.org/license/BSD-3-clause
 version: 0.0.2
servers:
  - url: /api
paths:
  /healthcheck:
    get:
      operationId: bookListerHealthCheck
      summary: Ensure BookLister API is running
      security: []
      responses:
        "200":
          description: BookLister API is up and running
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                status:
                  type: string
                  enum: ['RUNNING', 'DOWN']
              example:
                status: RUNNING

        "503":
         description: Bookister API has something wrong
         content:
            application/json:
              schema:
                type: object
                required:
                  - status
                status:
                  type: string
                  enum: ['RUNNING', 'DOWN']
              example:
                status: DOWN
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
