openapi: 3.1.0
info:
 title: bookLister API
 license:
   name: BSD-3 Clause
   url: https://opensource.org/license/BSD-3-clause
 version: 0.0.4
servers:
  - url: https://localhost:{port}/{basePath}
    description: localhost
    variables:
      port:
        enum:
          - '8080'
        default: '8080'
        descripton: what port the API is running on
      basePath:
        default: 'api'
paths:
  /healthcheck:
    get:
      operationId: bookListerHealthCheck
      summary: Ensure BookLister API is running
      security: []
      responses:
        "200":
          description: BookLister API is up and running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
              example:
                status: RUNNING
        "503":
         description: Bookister API has something wrong
         content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
              example:
                status: DOWN
components:
  schemas:
    HealthCheckResponse:
      type: object
      required:
        - status
      status:
        type: string
        enum: ['RUNNING', 'DOWN']
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
