name: CI Check

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    name: Build & Test booklister
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bookLister
        uses: actions/checkout@4

      - name: Setup JDK 26
        uses: actions/setup-java@4
        with:
          distribution: temurin
          java-version: "26"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew Runnable
        working-directory: middleware
        run: chmod +x gradlew
